# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    azure_whatsapp.tenant_id: '%env(AZURE_WHATSAPP_TENANT_ID)%'
    azure_whatsapp.client_id: '%env(AZURE_WHATSAPP_CLIENT_ID)%'
    azure_whatsapp.client_secret: '%env(AZURE_WHATSAPP_CLIENT_SECRET)%'
    azure_whatsapp.base_url: '%env(AZURE_WHATSAPP_BASE_URL)%'
    azure_whatsapp.channel_id: '%env(AZURE_WHATSAPP_CHANNEL_ID)%'
    app.uploads_dir: '%kernel.project_dir%/var/uploads'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\WhatsAppService:
        arguments:
            $logger: '@monolog.logger.whatsapp'
            $tenantId: '%azure_whatsapp.tenant_id%'
            $clientId: '%azure_whatsapp.client_id%'
            $clientSecret: '%azure_whatsapp.client_secret%'
            $baseUrl: '%azure_whatsapp.base_url%'
            $channelId: '%azure_whatsapp.channel_id%'

    App\Controller\Api\WhatsAppWebhookController:
        arguments:
            $logger: '@monolog.logger.whatsapp'

    App\Service\AttachmentStorage:
        arguments:
            $uploadsDir: '%app.uploads_dir%'
